### ISSUE TITLE
Socket Error, unable to establish a connection. Same tCam-mini works with the app on Windows

### ISSUE THREAD

**Issue by griffin175** [yaturner/tcamViewerRelease#23] opened 2023-03-02 23:33 UTC
![tCamViewer-alpha-socket-error](https://user-images.githubusercontent.com/56269216/222587976-18107208-d782-410d-b88e-80584ff31d39.jpg)

**Comment by griffin175** [comment] 2023-03-02 23:34
Hardware: Galaxy S10
OS: Android v12 - Snow Cone

**Comment by yaturner** [comment] 2023-03-02 23:39
This is a known problem caused by my fat fingers, I will have a new release
that connects properly by this weekend. I am sorry for the inconvience

**Comment by yaturner** [comment] 2023-03-04 17:16
Fixed in 0.3.3

**Closed as completed** 2023-04-07 13:59 UTC
Labels: QA
